cluster:
  name: ${cluster_name}

network.host: _site_,_lo_

path:
  data: /var/lib/elasticsearch
  logs: /var/log/elasticsearch

bootstrap:
  memory_lock: true

http:
  cors:
    enabled: true
    allow-origin: "*"

cloud.gce.project_id: ${project}
cloud.gce.zone: [${zones}]
discovery:
  seed_providers: gce

# config generated by Terraform provision
