cluster:
  name: ${cluster_name}

network.host: _site_,_lo_

path:
  data: /var/lib/elasticsearch
  logs: /var/log/elasticsearch

bootstrap:
  memory_lock: true

http:
  cors:
    enabled: true
    allow-origin: "*"

cloud.gce.project_id: ${project}
cloud.gce.zone: ${zone}
discovery:
  zen:
    hosts_provider: gce

cluster.initial_master_nodes: [${nodes}]

# config generated by Terraform provision
